# These are supported funding model platforms

custom: ["https://www.paypal.com/donate?hosted_button_id=6C6GG7DE5BCGS","Only.for.Brazilians''PIX''alanfinoty@gmail.com","Only.for.Brazilians''PIX''alanfinoty@live.com"]
